require:
  - solidus_dev_support/rubocop

inherit_from: .rubocop_todo.yml

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

FactoryBot/CreateList:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false

FactoryBot/FactoryNameStyle:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

FactoryBot/FactoryClassName:
  Enabled: false

FactoryBot/RedundantFactoryOption:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2
